### ISSUE TITLE
interface between binaries and AluVM

### ISSUE THREAD

**Issue by 6293** [AluVM/aluasm#2]
@dr-orlovsky It looks there are currently no way to load `.rex` and `.ald` files into AluVM. Do you imagine something on this? Maybe we can build `aluvm` executable on this repo which would work like following:

```bash
aluvm add ./build/miner@pandoracore.ald
aluvm exec ./build/all@lnpbp.rex
```

**Comment by dr-orlovsky** [comment]
Not exactly. AluVM should not load binaries since it does not support all required ISA extensions. The only thing that can load binaries is Alu runtime environments - and for that we will have [`alure` ](https://github.com/pandoracore/alure)

**Comment by 6293** [comment]
ah thanks, I forgot about the alure

**Comment by dr-orlovsky** [comment]
Just in case, I was giving more info about it here: https://www.youtube.com/watch?v=brfWta7XXFQ

The slides from the talk can be found here:
https://github.com/LNP-BP/presentations/blob/master/Presentation%20slides/AluVM.pdf
